name: Playwright Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout frontend repo
      uses: actions/checkout@v4
      with:
        path: frontend

    - name: Clone backend repo
      run: git clone https://github.com/TQS-voltconnect/backend.git backend

    - name: Clone deployment repo
      run: git clone https://github.com/TQS-voltconnect/deployment.git deployment

    - name: Start Docker Compose stack
      working-directory: deployment
      run: |
        docker compose up -d --wait
        sleep 15

    - name: Wait for frontend and backend
      run: npx wait-on http://localhost http://localhost:8080

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies and run tests
      working-directory: frontend
      run: |
        npm ci
        npx playwright install --with-deps
        npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
